### PR TITLE
Controlled + pass props + redux-form comp

### PR DESCRIPTION
**Pull request by romannep**
Solves #3 #5 
Updates described in README.md

### CODE REVIEW

**Comment by slavikdenis** [comment]
When could be this released?

**Comment by LoicMahieu** [comment]
Hi!
Thanks for PR and sorry to be late.

Could you remove the prop `fullWidth` ? There is no impact in the component. Furthermore since #19 , there is no more `<div />` around the `TextField`. It should fix the issue with `width`.

**Comment by romannep** [comment]
Oops.. already remove fork. Will try to check local files, restore and fix at weekend.

**Comment by romannep** [comment]
Can't bind restored repo to this PR, so make a new one.

**Pull request closed without merging**
