### PR TITLE
Support material ui 1.0 (material-ui-next)

### PR DESCRIPTION
**Pull request by motiko**
backwards compatible with old prop names if provided (hintText, floatingLabelText)
and support for new prop names (placeholder, label)
* move style to InputProps
* use babel-env preset

### CODE REVIEW

**Comment by LoicMahieu** [comment]
Hi @motiko 
Thanks for your PR! Looks great!
Since mui is still in beta, we could not publish this on master and as `latest` on npm.
I will create a `next` branch and publish it as `beta` on npm.

**Comment by motiko** [comment]
Sure, maybe it's worth adding a note about it in the readme since mui 1.0 is recommended for new projects.

**Comment by LoicMahieu** [comment]
`npm install material-ui-color-picker@next` should works

**Comment by LoicMahieu** [comment]
I am not actively use mui in my current projects. When mui will be released, feel free to open an issue ;)

**Comment by motiko** [comment]
Awesome, thank you for a great component.

**Comment by motiko** [comment]
@LoicMahieu I just tried `npm install material-ui-color-picker@next` 
for some reason it copies the src code. only if go to the directory in node_modules and run `npm install && npm  run build` it works.

**Comment by motiko** [comment]
i believe i found the solution to add prepare script ( at least it worked for me when installing from gtihub) 
see my last commit (im not sure if i have to open a new pr)

**Pull request merged**
